apiVersion: v1
kind: Pod
metadata:
  name: todoapp
  namespace: todoapp
spec:
  containers:
    - name: todoapp
      image: lambdda/todoapp:3.0.0
      ports:
        - containerPort: 8000
      readinessProbe:
        httpGet:
          path: /api/health/ready/
          port: 8000
        initialDelaySeconds: 5
        periodSeconds: 10
        failureThreshold: 3
      livenessProbe:
        httpGet:
          path: /api/health/live/
          port: 8000
        initialDelaySeconds: 10
        periodSeconds: 10
        failureThreshold: 3